### ISSUE TITLE
Innlesing av data som egen R-pakke/app?

### ISSUE THREAD

**Issue by areedv** [mong/qmongrdata#15]
Jeg ser opplagte ulemper med å ha innlesing av data som del av R-pakken qmongrdata. Om dette skal tilbys alle som melder inn data hadde det vært fint å kunne legge denne ut på mong.no som en egen app (i form av en docker kontainer) og da bør den "veie" så lite som mulig. Ka dokker trur?

**Comment by arnfinn** [comment]
Enig (tror jeg).

Ser for meg at `qmongrdata` kun inneholder denne appen til Kevin, og at denne appen spytter dataene opp i skyen en plass. Og at den kjøres på mongr.no. Er det ikke noe sånn vi ser for oss?

**Comment by areedv** [comment]
Appen er nettopp den jeg ønsker i en egen R-pakke av hensyn til lett å kunne stues inn i en kontainer (uten alt det andre som ligger i qmongrdata)

**Comment by arnfinn** [comment]
Ja. Jeg tenkte vel bare at `qmongrdata` var denne R-pakken, men kanskje like greit å lage en ny en?

**Comment by areedv** [comment]
Tror det kan være greit å ha en qmongrdata (med opprinnelig formål) å falle tilbake på om sentralisert lagring ikke virker som det skal

**Comment by areedv** [comment]
Dette blir forøvrig også en applikasjon som vi også må legge bak en pålogging...

**Comment by arnfinn** [comment]
Høres fint ut @areedv! Har en av dere tid til å lage denne pakken? Forslag til navn @kevinthon?

**Comment by areedv** [comment]
Jeg kan sette den opp og lage rammeverk (må bla ha en profil-side og database-funksjoner) så kan ev @kevinthon flytte sin kode fra qmongrdata. Jeg foreslår navnet __imongr__ siden det er hver enkelt sitt bidrag til innhold på qmongr :-)

**Comment by arnfinn** [comment]
**imongr** høres fint ut:)

**Comment by arnfinn** [comment]
Jeg har opprettet en PR (#16) som sletter appen her. Venter på godkjennelse av @kevinthon, men ser ikke ut til at han lever på github, i motsetning til oss andre.

**Comment by kevinthon** [comment]
Vi vil jo gjerne fiske data ut fra registrene, kan phishmongr være et alternativ?

**Comment by arnfinn** [comment]
Kanskje spare `phishmongr` til den pakken som automatisk skal fiske ut data fra registre (hvis vi får det etterhvert)?
