### ISSUE TITLE
Add nkr_nakke as csv

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongrdata#47]
Either by something like this:
```R
library(nakke)
RegData <- NakkeRegDataSQL()
RegData <- NakkePreprosess(RegData)

KvalIndDataNakke <- tilretteleggDataNakke(RegData = RegData, datoFra = "2014-01-01", aar=0)
write.csv2(KvalIndDataNakke, file = "data-raw/nakke.csv")
```
or convert nakke data from `KvalIndData` to csv.

**Comment by arnfinn** [comment]
Currently the following org_nr are in the data, and have to be changed:
- 999998 (Oslofjordklinikken, either Sandnes 913758862 or Sandvika 991835083)
- 4000020 (Stavanger, 974703300)

**Comment by lenaringstado** [comment]
orgid'er er endret ihht spesifikasjon, men dette gir feilmelding i imongr. Følges opp.

**Comment by lenaringstado** [comment]
Nye data med nye indikatornavn i data-raw
